name: PlatformIO CI - Build for Arduino

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      # rename src/secrets.h.example to src/secrets.h, to use a dummy values during build
      - name: Copy secrets.h
        run: cp ./controller/tea_poor/src/secrets.h.example ./controller/tea_poor/src/secrets.h

      - name: Build PlatformIO Project for Arduino
        working-directory: ./controller/tea_poor
        run: pio run -e uno_r4_wifi
